#!/bin/sh
# *******************************************************
# l6_reval_2.sh
# 3秒おき、V\$ASM_OPERATIONの確認
# gridで実行
# *****************************************************

echo "gridユーザーで実行します。gridユーザーであればEnterキーを押してください"
read
echo "sqlplus /nolog"
sqlplus /nolog <<EOF
prompt connect / as sysasm
connect / as sysasm

set time on

--ALTER DISKGROUP DATA ADD DISK '/dev/sdh1';

prompt SELECT PASS,STATE,SOFAR,EST_WORK,EST_MINUTES FROM V\$ASM_OPERATION;
SELECT PASS,STATE,SOFAR,EST_WORK,EST_MINUTES FROM V\$ASM_OPERATION;
!sleep 3
SELECT PASS,STATE,SOFAR,EST_WORK,EST_MINUTES FROM V\$ASM_OPERATION;
!sleep 3
SELECT PASS,STATE,SOFAR,EST_WORK,EST_MINUTES FROM V\$ASM_OPERATION;
!sleep 3
SELECT PASS,STATE,SOFAR,EST_WORK,EST_MINUTES FROM V\$ASM_OPERATION;
!sleep 3
SELECT PASS,STATE,SOFAR,EST_WORK,EST_MINUTES FROM V\$ASM_OPERATION;
!sleep 3
SELECT PASS,STATE,SOFAR,EST_WORK,EST_MINUTES FROM V\$ASM_OPERATION;
!sleep 3
SELECT PASS,STATE,SOFAR,EST_WORK,EST_MINUTES FROM V\$ASM_OPERATION;
!sleep 3
SELECT PASS,STATE,SOFAR,EST_WORK,EST_MINUTES FROM V\$ASM_OPERATION;
!sleep 3
SELECT PASS,STATE,SOFAR,EST_WORK,EST_MINUTES FROM V\$ASM_OPERATION;
!sleep 3
SELECT PASS,STATE,SOFAR,EST_WORK,EST_MINUTES FROM V\$ASM_OPERATION;
!sleep 3
SELECT PASS,STATE,SOFAR,EST_WORK,EST_MINUTES FROM V\$ASM_OPERATION;
!sleep 3
SELECT PASS,STATE,SOFAR,EST_WORK,EST_MINUTES FROM V\$ASM_OPERATION;
!sleep 3
SELECT PASS,STATE,SOFAR,EST_WORK,EST_MINUTES FROM V\$ASM_OPERATION;
!sleep 3
SELECT PASS,STATE,SOFAR,EST_WORK,EST_MINUTES FROM V\$ASM_OPERATION;
!sleep 3
SELECT PASS,STATE,SOFAR,EST_WORK,EST_MINUTES FROM V\$ASM_OPERATION;
!sleep 3
SELECT PASS,STATE,SOFAR,EST_WORK,EST_MINUTES FROM V\$ASM_OPERATION;
!sleep 3
SELECT PASS,STATE,SOFAR,EST_WORK,EST_MINUTES FROM V\$ASM_OPERATION;
!sleep 3
SELECT PASS,STATE,SOFAR,EST_WORK,EST_MINUTES FROM V\$ASM_OPERATION;
!sleep 3
SELECT PASS,STATE,SOFAR,EST_WORK,EST_MINUTES FROM V\$ASM_OPERATION;
!sleep 3
SELECT PASS,STATE,SOFAR,EST_WORK,EST_MINUTES FROM V\$ASM_OPERATION;
!sleep 3
SELECT PASS,STATE,SOFAR,EST_WORK,EST_MINUTES FROM V\$ASM_OPERATION;
!sleep 3
SELECT PASS,STATE,SOFAR,EST_WORK,EST_MINUTES FROM V\$ASM_OPERATION;
!sleep 3
exit 
EOF

